// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/workspace/scm-yao/xgen/node_modules/.pnpm/@umijs+renderer-react@4.0.6_3127e14b773d120059b26c840c637d72/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/workspace/scm-yao/xgen/node_modules/.pnpm/@umijs+renderer-react@4.0.6_3127e14b773d120059b26c840c637d72/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/workspace/scm-yao/xgen/node_modules/.pnpm/umi@4.0.68_@babel+core@7.28_c2a960775cb8e7a3dac5e49f07729f4c/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// plugins
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'D:/workspace/scm-yao/xgen/packages/xgen/.umi/plugin-locale';
// plugins types.d.ts
export * from 'D:/workspace/scm-yao/xgen/packages/xgen/.umi/plugin-antd/types.d';
