// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"assistants/create/index":{"path":"assistants/create","id":"assistants/create/index","parentId":"@@/global-layout"},"login/user/$is/index":{"path":"login/user/:is","id":"login/user/$is/index","parentId":"@@/global-layout"},"assistants/detail/$":{"path":"assistants/detail/*","id":"assistants/detail/$","parentId":"@@/global-layout"},"login/admin/index":{"path":"login/admin","id":"login/admin/index","parentId":"@@/global-layout"},"assistants/index":{"path":"assistants","id":"assistants/index","parentId":"@@/global-layout"},"login/user/index":{"path":"login/user","id":"login/user/index","parentId":"@@/global-layout"},"iframe/index":{"path":"iframe","id":"iframe/index","parentId":"@@/global-layout"},"auth/index":{"path":"auth","id":"auth/index","parentId":"@@/global-layout"},"logo/index":{"path":"logo","id":"logo/index","parentId":"@@/global-layout"},"404/index":{"path":"*","id":"404/index","parentId":"@@/global-layout"},"setting/$":{"path":"setting/*","id":"setting/$","parentId":"@@/global-layout"},"chat/$":{"path":"chat/*","id":"chat/$","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"web/$":{"path":"web/*","id":"web/$","parentId":"@@/global-layout"},"x/$":{"path":"x/*","id":"x/$","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'assistants/create/index': React.lazy(() => import(/* webpackChunkName: "p__assistants__create__index" */'../../pages/assistants/create/index.tsx')),
'login/user/$is/index': React.lazy(() => import(/* webpackChunkName: "p__login__user__$is__index" */'../../pages/login/user/$is/index.tsx')),
'assistants/detail/$': React.lazy(() => import(/* webpackChunkName: "p__assistants__detail__$" */'../../pages/assistants/detail/$.tsx')),
'login/admin/index': React.lazy(() => import(/* webpackChunkName: "p__login__admin__index" */'../../pages/login/admin/index.tsx')),
'assistants/index': React.lazy(() => import(/* webpackChunkName: "p__assistants__index" */'../../pages/assistants/index.tsx')),
'login/user/index': React.lazy(() => import(/* webpackChunkName: "p__login__user__index" */'../../pages/login/user/index.tsx')),
'iframe/index': React.lazy(() => import(/* webpackChunkName: "p__iframe__index" */'../../pages/iframe/index.tsx')),
'auth/index': React.lazy(() => import(/* webpackChunkName: "p__auth__index" */'../../pages/auth/index.tsx')),
'logo/index': React.lazy(() => import(/* webpackChunkName: "p__logo__index" */'../../pages/logo/index.tsx')),
'404/index': React.lazy(() => import(/* webpackChunkName: "p__404__index" */'../../pages/404/index.tsx')),
'setting/$': React.lazy(() => import(/* webpackChunkName: "p__setting__$" */'../../pages/setting/$.tsx')),
'chat/$': React.lazy(() => import(/* webpackChunkName: "p__chat__$" */'../../pages/chat/$.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "p__index" */'../../pages/index.tsx')),
'web/$': React.lazy(() => import(/* webpackChunkName: "p__web__$" */'../../pages/web/$.tsx')),
'x/$': React.lazy(() => import(/* webpackChunkName: "p__x__$" */'../../pages/x/$.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/workspace/scm-yao/xgen/packages/xgen/layouts/index.tsx')),
},
  };
}
